### ISSUE TITLE
Registered datasets are being shown as unregistered

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/pyguess#3] opened 2015-07-02 11:50 UTC
If I use this server address in the mass_import page:
http://maps.iguess.tudor.lu/cgi-bin/mapserv?map=/srv/mapserv/MapFiles/LB_localOWS_test.map

It lists all datasets as unregistered (pink background), but most of them are actually registered and listed in Registered Datasets page (main Data Manager list).

**Comment by ldesousa** [comment] 2015-07-13 12:43
Only the datasets for the current city should be shown.

**Comment by zajdaf** [comment] 2015-07-22 13:58
Duplicate of #2

**Closed by zajdaf** 2015-07-22 13:58 UTC
Labels: medium
