### ISSUE TITLE
Exception accessing Maps page with Firefox

### ISSUE THREAD

**Issue by ldesousa** [ERIN-LIST/pyguess#62] opened 2015-09-16 07:18 UTC
![mapsfirefox](https://cloud.githubusercontent.com/assets/1137878/9898608/dd84bb8c-5c53-11e5-90d2-d2976f762ca2.png)

**Comment by uleopold** [comment] 2015-09-16 07:23
I get a similar exception in Chromium.

**Comment by uleopold** [comment] 2015-09-17 07:57
The Chromium and the Firefox exception problem seems to be associated to not being logged in. Once I am logged in. The exception is gone.

Luís, can you confirm this on your side too?

**Comment by MStefas** [comment] 2015-09-17 13:00
should be related with the fix done for the #61

**Comment by MStefas** [comment] 2015-09-21 15:07
Do you confirm the this issue can be closed ?

**Comment by uleopold** [comment] 2015-09-21 15:13
pre {display: block;font-family: Helvetica Neue, Helvetica, Arial, sans-serif;white-space: pre-wrap;margin: 1em 0;}I can confirm. Luís, can you confirm too? 

Sent from IBM VerseStefas Mickaël --- Re: [pyguess] Exception accessing Maps page with Firefox (#62) --- From:"Stefas Mickaël" <notifications@github.com>To:"ERIN-LIST/pyguess" <pyguess@noreply.github.com>Cc:"Ulrich Leopold" <ulrich.leopold@list.lu>Date:Mon, 21 Sep 2015 17:07Subject:Re: [pyguess] Exception accessing Maps page with Firefox (#62)Do you confirm the this issue can be closed ?

**Comment by mdlux** [comment] 2015-09-22 08:45
Closing

**Closed by mdlux** 2015-09-22 08:45 UTC
Labels: high
